version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DB_URL=jdbc:postgresql://db:5432/nazwaBazy
#      - DB_USERNAME=uzytkownikBazy
#      - DB_PASSWORD=hasloBazy
#    depends_on:
#      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
