name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Deploy on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Usuń istniejący kontener (jeśli istnieje), bez błędów jeśli nie istnieje
          docker stop my-container || true
          docker rm my-container || true

          # Usuń lokalny obraz (jeśli istnieje), bez błędów jeśli nie istnieje
          docker rmi kathelan/budgetify-be:latest || true

          # Pobierz najnowszy obraz
          docker pull kathelan/budgetify-be:latest

          # Uruchom kontener z nowym obrazem
          docker run -d --restart always --name my-container \
          -p 0.0.0.0:8080:8080 \
          -e DB_URL=${{ secrets.DB_URL }} \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          kathelan/budgetify-be:latest
