name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Prepare tags
      id: prep
      run: |
        echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          kathelan/budgetify-be:latest
          kathelan/budgetify-be:${{ env.DATE }}-${{ env.COMMIT_SHA }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ env.DATE }}
