name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # To trigger the workflow on tag push that matches the semantic versioning, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract branch name or tag
      id: ref
      run: echo "::set-output name=ref::$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')"
    
    - name: Extract version
      id: semver
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/v})"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          kathelan/budgetify-be:latest
          kathelan/budgetify-be:${{ steps.ref.outputs.ref }}
          kathelan/budgetify-be:${{ steps.semver.outputs.version }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ steps.date.outputs.date }}
